language: node_js
node_js:
- '4'
branches:
  only:
  - master
before_install:
- npm install -g serverless@beta
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
notifications:
  slack:
    secure: N6fR8mCQ7IY9SrsW/nCX++RX5PNBIwpfBrqebxszkf02p22wW8p7GvTq6E5s3Kic5hhgsodS5cdo9Xl56wTcPUygvFT5F1+O3pZeZrGLiLhsa//ho3Od8+JwlQasAHF2zM/jE3vWxetvCL2TEui9SUwmrJnWLJzMvf7dl09hHfVGZvribUdfITBXYoOYre7cWJw4MGnnbKGoXoRErDQJHuk64afYlwG0ixWktTXcc0pPrdzXbFLVEgJwQQEXCpIU+65ykycYnXYZIJn4+fwdRbp6CfPvLwascGg0dWsdMd1kWNYjHMjgy16l4z0SIhXEw9QA/yjn45DS11Z15kqhmpkrKqULuj8To6aqpf0BXdL5B/ats6mky/ayLTQnwzN/6gGEonpR4D2vo8mxq+18ldXbQaHvarXwGAx491QJzQ4w+U0acWqgh1RkbUbBcWSbEbQRHC3X3ddrKGzBiNENERngb4UGEsi8dOZeVP4IORf08Ay3UuEb+eJ29MO5Sc1XZvivZYRbgck0G6eBLskshDafu8bPHk/P56BV9tTgrCSaTdnd/7VBceDrM6oqwBYMUpu7x0785rBiDyFVeK2C8vKHVpDwMZd40KRBsYi9Il46K7TUbGOjpXgtLtbu86sAgnUoVKqeI+XZTEFv+MO1D5nlsSuF2b5cRSiLNSzzzAo=
