service: sls-aws-hello-world

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#  exclude:
#    - exclude-me.js
#  artifact: my-service-code.zip

functions:
  test:
    handler: handler.test
    events:
      - http:
          path: test
          method: post
